name: ax
repository: https://github.com/malmi/ax

packages:
  - packages/**
  - "tests/*"

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  analyze:
    description: Run `dart analyze` in all packages.
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos

  format:
    description: Format code everywhere
    run: dart pub global run flutter_plugin_tools format

  lint:
    description: Run all static analysis checks.
    run: melos run analyze && melos run format

  clean:deep:
    description: Clean things very deeply, can be used to establish "pristine checkout" status.
    run: git clean -x -d -f -q

  qualitycheck:
    description: Run all targets generally expected in CI for a full local quality check.
    run: |
      melos run clean:deep && \
      melos clean && \
      melos bootstrap && \
      melos run lint:all && \
      melos run build:all && \
      melos run test:all

  # Additional cleanup lifecycle script, executed when `melos clean` is run.
  postclean: >
    melos exec -c 6 -- "flutter clean"
