name: Setup
description: Setup Flutter and everything else

runs:
  using: composite
  steps:
    - name: 📥 Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: beta
    - name: ⚡ Activate melos
      shell: sh
      run: |
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
        pub global activate melos
    - name: 👀 Bootstrap melos
      shell: sh
      run: melos bootstrap
