name: Validate
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3
      - name: 📥 Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: ⚡ Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          pub global activate melos
      - name: 👀 Bootstrap melos
        run: melos bootstrap
      - name: 🔬 Analyze package
        run: melos exec -- flutter analyze

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3
      - name: 📥 Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: ⚡ Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          pub global activate melos
      - name: 👀 Bootstrap melos
        run: melos bootstrap
      - name: 🔎 Validate formatting
        run: |
          melos exec -- dart format -o write .
          ./.github/workflows/scripts/validate-formatting.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3
      - name: 📥 Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: ⚡ Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          pub global activate melos
      - name: 👀 Bootstrap melos
        run: melos bootstrap
      - name: ⚡ Run tests
        run: melos exec --dir-exists=test -- flutter test
