name: ax
description: Poor folks version of actors for a nice state management that is more event driven and should be used if you are an advocate of event sourcing.
version: 0.0.1
repository: https://github.com/collabree/ax

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  rxdart: ^0.27.4
  rxdart_ext: ^0.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
