name: ax
description: Poor people version of actors for a nice state mangement, which is more event-driven and should be used if you are an advocate of event-sourcing.
version: 0.0.1
homepage: https://www.malcharek.eu/ax

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection:
  rxdart:
  rxdart_ext:
  time_machine:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
